### ISSUE TITLE
requestorresponse是none怎么办

### ISSUE THREAD

**Issue by fog895559** [f0ng/autoDecoder-usages#2]
想请问下，为什么接口调试那块的时候获取requestorresponse是none，因为我要写的代码是需要区分开request还是response的，request有好几个参数需要解密，response只有返回数据包的字符串需要解密

**Comment by f0ng** [comment]
autoDecoder需要勾选`请求响应不同加解密`即可获取到requestorresponse参数

**Comment by fog895559** [comment]
> autoDecoder需要勾选`请求响应不同加解密`即可获取到requestorresponse参数

好的，谢谢，接口调试已经OK了，但是repeater不会自动加解密，可以帮忙看看吗？方便加个vx吗？我这上传不了图片

**Comment by f0ng** [comment]
v`f-f0ng`

**Comment by f0ng** [comment]
原因在于关键字的选取上
